"""add guest_threads

Revision ID: 2306cf1eb24c
Revises: adf8008f4506
Create Date: 2026-04-12 14:19:08.592536

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2306cf1eb24c"
down_revision: Union[str, Sequence[str], None] = "adf8008f4506"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "guest_threads",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("guest_id", sa.String(length=36), nullable=False),
        sa.Column("thread_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("thread_id"),
        schema="tatoh",
    )
    op.create_index(
        op.f("ix_tatoh_guest_threads_guest_id"),
        "guest_threads",
        ["guest_id"],
        unique=False,
        schema="tatoh",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_tatoh_guest_threads_guest_id"),
        table_name="guest_threads",
        schema="tatoh",
    )
    op.drop_table("guest_threads", schema="tatoh")
    # ### end Alembic commands ###
