"""add_room_photos

Revision ID: adf8008f4506
Revises: d621e2cda7cb
Create Date: 2026-03-13 01:18:42.115099

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "adf8008f4506"
down_revision: Union[str, Sequence[str], None] = "d621e2cda7cb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "room_photos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("room_id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["room_id"], ["tatoh.rooms.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="tatoh",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("room_photos", schema="tatoh")
    # ### end Alembic commands ###
