"""create rooms schedules and knowledge tables in tatoh schema

Revision ID: d621e2cda7cb
Revises:
Create Date: 2026-03-11 23:26:08.649212

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d621e2cda7cb"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS tatoh")
    op.create_table(
        "boat_schedules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("origin", sa.String(length=100), nullable=False),
        sa.Column("destination", sa.String(length=100), nullable=False),
        sa.Column("departure", sa.Time(), nullable=False),
        sa.Column("arrival", sa.Time(), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("infant_price", sa.Integer(), nullable=False),
        sa.Column("young_children_price", sa.Integer(), nullable=False),
        sa.Column("is_vip", sa.Boolean(), nullable=False),
        sa.Column("is_direct", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="tatoh",
    )
    op.create_table(
        "bus_schedules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("origin", sa.String(length=100), nullable=False),
        sa.Column("destination", sa.String(length=100), nullable=False),
        sa.Column("departure", sa.Time(), nullable=False),
        sa.Column("arrival", sa.Time(), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="tatoh",
    )
    op.create_table(
        "knowledge_documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("image_urls", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
        schema="tatoh",
    )
    op.create_table(
        "rooms",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("room_name", sa.String(length=10), nullable=False),
        sa.Column("room_type", sa.String(length=50), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("bed_queen", sa.Integer(), nullable=False),
        sa.Column("bed_single", sa.Integer(), nullable=False),
        sa.Column("baths", sa.Integer(), nullable=False),
        sa.Column("size", sa.Float(), nullable=False),
        sa.Column("price_weekdays", sa.Float(), nullable=False),
        sa.Column("price_weekends_holidays", sa.Float(), nullable=False),
        sa.Column("price_ny_songkran", sa.Float(), nullable=False),
        sa.Column("max_guests", sa.Integer(), nullable=False),
        sa.Column("steps_to_beach", sa.Integer(), nullable=False),
        sa.Column("sea_view", sa.Integer(), nullable=False),
        sa.Column("privacy", sa.Integer(), nullable=False),
        sa.Column("steps_to_restaurant", sa.Integer(), nullable=False),
        sa.Column("room_design", sa.Integer(), nullable=False),
        sa.Column("room_newness", sa.Integer(), nullable=False),
        sa.Column("tags", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("room_name"),
        schema="tatoh",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("rooms", schema="tatoh")
    op.drop_table("knowledge_documents", schema="tatoh")
    op.drop_table("bus_schedules", schema="tatoh")
    op.drop_table("boat_schedules", schema="tatoh")
    op.execute("DROP SCHEMA IF EXISTS tatoh")
    # ### end Alembic commands ###
