/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KnowledgeRouteRouteImport } from './routes/knowledge/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KnowledgeIndexRouteImport } from './routes/knowledge/index'
import { Route as KnowledgeRoomsIndexRouteImport } from './routes/knowledge/rooms/index'
import { Route as KnowledgeConversationsIndexRouteImport } from './routes/knowledge/conversations/index'
import { Route as KnowledgeBusSchedulesIndexRouteImport } from './routes/knowledge/bus-schedules/index'
import { Route as KnowledgeBoatSchedulesIndexRouteImport } from './routes/knowledge/boat-schedules/index'
import { Route as KnowledgeRoomsNewRouteImport } from './routes/knowledge/rooms/new'
import { Route as KnowledgeRoomsIdRouteImport } from './routes/knowledge/rooms/$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRouteRoute = KnowledgeRouteRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeIndexRoute = KnowledgeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KnowledgeRouteRoute,
} as any)
const KnowledgeRoomsIndexRoute = KnowledgeRoomsIndexRouteImport.update({
  id: '/rooms/',
  path: '/rooms/',
  getParentRoute: () => KnowledgeRouteRoute,
} as any)
const KnowledgeConversationsIndexRoute =
  KnowledgeConversationsIndexRouteImport.update({
    id: '/conversations/',
    path: '/conversations/',
    getParentRoute: () => KnowledgeRouteRoute,
  } as any)
const KnowledgeBusSchedulesIndexRoute =
  KnowledgeBusSchedulesIndexRouteImport.update({
    id: '/bus-schedules/',
    path: '/bus-schedules/',
    getParentRoute: () => KnowledgeRouteRoute,
  } as any)
const KnowledgeBoatSchedulesIndexRoute =
  KnowledgeBoatSchedulesIndexRouteImport.update({
    id: '/boat-schedules/',
    path: '/boat-schedules/',
    getParentRoute: () => KnowledgeRouteRoute,
  } as any)
const KnowledgeRoomsNewRoute = KnowledgeRoomsNewRouteImport.update({
  id: '/rooms/new',
  path: '/rooms/new',
  getParentRoute: () => KnowledgeRouteRoute,
} as any)
const KnowledgeRoomsIdRoute = KnowledgeRoomsIdRouteImport.update({
  id: '/rooms/$id',
  path: '/rooms/$id',
  getParentRoute: () => KnowledgeRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/knowledge': typeof KnowledgeRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/knowledge/rooms/$id': typeof KnowledgeRoomsIdRoute
  '/knowledge/rooms/new': typeof KnowledgeRoomsNewRoute
  '/knowledge/boat-schedules/': typeof KnowledgeBoatSchedulesIndexRoute
  '/knowledge/bus-schedules/': typeof KnowledgeBusSchedulesIndexRoute
  '/knowledge/conversations/': typeof KnowledgeConversationsIndexRoute
  '/knowledge/rooms/': typeof KnowledgeRoomsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/knowledge': typeof KnowledgeIndexRoute
  '/knowledge/rooms/$id': typeof KnowledgeRoomsIdRoute
  '/knowledge/rooms/new': typeof KnowledgeRoomsNewRoute
  '/knowledge/boat-schedules': typeof KnowledgeBoatSchedulesIndexRoute
  '/knowledge/bus-schedules': typeof KnowledgeBusSchedulesIndexRoute
  '/knowledge/conversations': typeof KnowledgeConversationsIndexRoute
  '/knowledge/rooms': typeof KnowledgeRoomsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/knowledge': typeof KnowledgeRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/knowledge/rooms/$id': typeof KnowledgeRoomsIdRoute
  '/knowledge/rooms/new': typeof KnowledgeRoomsNewRoute
  '/knowledge/boat-schedules/': typeof KnowledgeBoatSchedulesIndexRoute
  '/knowledge/bus-schedules/': typeof KnowledgeBusSchedulesIndexRoute
  '/knowledge/conversations/': typeof KnowledgeConversationsIndexRoute
  '/knowledge/rooms/': typeof KnowledgeRoomsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/knowledge'
    | '/login'
    | '/knowledge/'
    | '/knowledge/rooms/$id'
    | '/knowledge/rooms/new'
    | '/knowledge/boat-schedules/'
    | '/knowledge/bus-schedules/'
    | '/knowledge/conversations/'
    | '/knowledge/rooms/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/knowledge'
    | '/knowledge/rooms/$id'
    | '/knowledge/rooms/new'
    | '/knowledge/boat-schedules'
    | '/knowledge/bus-schedules'
    | '/knowledge/conversations'
    | '/knowledge/rooms'
  id:
    | '__root__'
    | '/'
    | '/knowledge'
    | '/login'
    | '/knowledge/'
    | '/knowledge/rooms/$id'
    | '/knowledge/rooms/new'
    | '/knowledge/boat-schedules/'
    | '/knowledge/bus-schedules/'
    | '/knowledge/conversations/'
    | '/knowledge/rooms/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KnowledgeRouteRoute: typeof KnowledgeRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/': {
      id: '/knowledge/'
      path: '/'
      fullPath: '/knowledge/'
      preLoaderRoute: typeof KnowledgeIndexRouteImport
      parentRoute: typeof KnowledgeRouteRoute
    }
    '/knowledge/rooms/': {
      id: '/knowledge/rooms/'
      path: '/rooms'
      fullPath: '/knowledge/rooms/'
      preLoaderRoute: typeof KnowledgeRoomsIndexRouteImport
      parentRoute: typeof KnowledgeRouteRoute
    }
    '/knowledge/conversations/': {
      id: '/knowledge/conversations/'
      path: '/conversations'
      fullPath: '/knowledge/conversations/'
      preLoaderRoute: typeof KnowledgeConversationsIndexRouteImport
      parentRoute: typeof KnowledgeRouteRoute
    }
    '/knowledge/bus-schedules/': {
      id: '/knowledge/bus-schedules/'
      path: '/bus-schedules'
      fullPath: '/knowledge/bus-schedules/'
      preLoaderRoute: typeof KnowledgeBusSchedulesIndexRouteImport
      parentRoute: typeof KnowledgeRouteRoute
    }
    '/knowledge/boat-schedules/': {
      id: '/knowledge/boat-schedules/'
      path: '/boat-schedules'
      fullPath: '/knowledge/boat-schedules/'
      preLoaderRoute: typeof KnowledgeBoatSchedulesIndexRouteImport
      parentRoute: typeof KnowledgeRouteRoute
    }
    '/knowledge/rooms/new': {
      id: '/knowledge/rooms/new'
      path: '/rooms/new'
      fullPath: '/knowledge/rooms/new'
      preLoaderRoute: typeof KnowledgeRoomsNewRouteImport
      parentRoute: typeof KnowledgeRouteRoute
    }
    '/knowledge/rooms/$id': {
      id: '/knowledge/rooms/$id'
      path: '/rooms/$id'
      fullPath: '/knowledge/rooms/$id'
      preLoaderRoute: typeof KnowledgeRoomsIdRouteImport
      parentRoute: typeof KnowledgeRouteRoute
    }
  }
}

interface KnowledgeRouteRouteChildren {
  KnowledgeIndexRoute: typeof KnowledgeIndexRoute
  KnowledgeRoomsIdRoute: typeof KnowledgeRoomsIdRoute
  KnowledgeRoomsNewRoute: typeof KnowledgeRoomsNewRoute
  KnowledgeBoatSchedulesIndexRoute: typeof KnowledgeBoatSchedulesIndexRoute
  KnowledgeBusSchedulesIndexRoute: typeof KnowledgeBusSchedulesIndexRoute
  KnowledgeConversationsIndexRoute: typeof KnowledgeConversationsIndexRoute
  KnowledgeRoomsIndexRoute: typeof KnowledgeRoomsIndexRoute
}

const KnowledgeRouteRouteChildren: KnowledgeRouteRouteChildren = {
  KnowledgeIndexRoute: KnowledgeIndexRoute,
  KnowledgeRoomsIdRoute: KnowledgeRoomsIdRoute,
  KnowledgeRoomsNewRoute: KnowledgeRoomsNewRoute,
  KnowledgeBoatSchedulesIndexRoute: KnowledgeBoatSchedulesIndexRoute,
  KnowledgeBusSchedulesIndexRoute: KnowledgeBusSchedulesIndexRoute,
  KnowledgeConversationsIndexRoute: KnowledgeConversationsIndexRoute,
  KnowledgeRoomsIndexRoute: KnowledgeRoomsIndexRoute,
}

const KnowledgeRouteRouteWithChildren = KnowledgeRouteRoute._addFileChildren(
  KnowledgeRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KnowledgeRouteRoute: KnowledgeRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
