services:
  # Temporarily re-expose port 80 so you can view it on your Mac
  frontend:
    ports:
      - "80:80"
  
  # Tell Docker not to start the tunnel when testing locally
  cloudflared:
    profiles: ["production"]

  # Expose database for local native Python commands (like migrations)
  db:
    ports:
      - "5431:5432"
